sudo: required
services:
  - docker

before_install:
  - docker build -t jet090892/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jet090892/react-test npm test

after_success:
  - docker build -t jet090892/multi-client ./client
  - docker build -t jet090892/multi-nginx ./nginx
  - docker build -t jet090892/multi-server ./server
  - docker build -t jet090892/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jet090892/multi-client
  - docker push jet090892/multi-nginx
  - docker push jet090892/multi-server
  - docker push jet090892/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-560251225732
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY